version: "3"
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:8000
    volumes:
      - ./:/usr/src/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres
    env_file:
        - ./.env.development

  postgres:
    image: postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data
    env_file:
        - ./.env.development

volumes:
  postgres-db:
